### PR TITLE
Rename uhk right project

### PR DESCRIPTION
**Pull request by mondalaci**
Renamed the `uhk-right` project name to `uhk-right-karel` so that two projects can coexist in MCUXpresso IDE.

Strangely, the redefinition of `layerLedIds` and `iconLedIds` surfaced after making the above change, so I've fixed it in the second commit.

### CODE REVIEW

**Comment by kareltucek** [comment]
Good idea, Thanks!

The redefinition was caused by bad merge on my side (and I guess it was already present when you checkouted the repo). Sorry about that!
